import type { LeadershipProfile } from "../types/leadership";

/** Anonymous preview slots. Not approved people, and not used in a publishable build. */
export const leadershipDrafts: LeadershipProfile[] = [
  {
    id: "profile-01",
    order: 1,
    group: "investment-operations",
    fullName: "Sofiia Tkachenko",
    title: "Managing Partner",
    relationship: null,
    biography: null,
    proposedRemit: "Investment strategy, capital allocation and founder relationships.",
    portrait: {
      src: "/images/leadership-managing-partner.jpg",
      alt: "Sofiia Tkachenko",
      objectPosition: "center 22%",
    },
    profileApproved: false,
    portraitApproved: true,
    portraitLabel: "PORTRAIT 01",
    draftStatus: "APPOINTMENT NOT CONFIRMED",
  },
  {
    id: "profile-02",
    order: 2,
    group: "investment-operations",
    fullName: "Vladyslav Blyzniuk",
    title: "CEO, Partner",
    relationship: null,
    biography: null,
    proposedRemit: "Payment-sector assessment and practical operating priorities.",
    portrait: {
      src: "/images/leadership-partner.png",
      alt: "Vladyslav Blyzniuk",
      objectPosition: "center 18%",
    },
    profileApproved: false,
    portraitApproved: true,
    portraitLabel: "PORTRAIT 02",
    draftStatus: "APPOINTMENT NOT CONFIRMED",
  },
  {
    id: "profile-07",
    order: 3,
    group: "investment-operations",
    fullName: "Vadym Nemyrytskyi",
    title: "Managing Director, Partner",
    relationship: null,
    biography: null,
    proposedRemit: "Board leadership, governance and strategic direction.",
    portrait: {
      src: "/images/leadership-chairman-president.jpg",
      alt: "Vadym Nemyrytskyi",
      objectPosition: "center 28%",
    },
    profileApproved: false,
    portraitApproved: true,
    portraitLabel: "PORTRAIT 07",
    draftStatus: "APPOINTMENT NOT CONFIRMED",
  },
  {
    id: "profile-03",
    order: 4,
    group: "investment-operations",
    fullName: "Elina Zelinko",
    title: "CIO",
    relationship: null,
    biography: null,
    proposedRemit: "Financial reporting, operating controls and administration.",
    portrait: {
      src: "/images/leadership-cio.jpg",
      alt: "Elina Zelinko",
      objectPosition: "center 20%",
    },
    profileApproved: false,
    portraitApproved: true,
    portraitLabel: "PORTRAIT 03",
    draftStatus: "APPOINTMENT NOT CONFIRMED",
  },
  {
    id: "profile-04",
    order: 5,
    group: "external-advisory",
    fullName: null,
    title: "Regulatory & Compliance Advisor",
    relationship: null,
    biography: null,
    proposedRemit: "Jurisdiction-specific legal and regulatory review within an agreed scope.",
    profileApproved: false,
    portraitApproved: false,
    portraitLabel: "PORTRAIT 04",
    draftStatus: "EXTERNAL ROLE PROPOSAL",
  },
  {
    id: "profile-05",
    order: 6,
    group: "external-advisory",
    fullName: null,
    title: "Technology & Security Advisor",
    relationship: null,
    biography: null,
    proposedRemit: "Authorized technical assessment and security review.",
    profileApproved: false,
    portraitApproved: false,
    portraitLabel: "PORTRAIT 05",
    draftStatus: "EXTERNAL ROLE PROPOSAL",
  },
  {
    id: "profile-06",
    order: 7,
    group: "external-advisory",
    fullName: null,
    title: "Regional Payments Advisor",
    relationship: null,
    biography: null,
    proposedRemit: "Local payment context and settlement-network understanding.",
    profileApproved: false,
    portraitApproved: false,
    portraitLabel: "PORTRAIT 06",
    draftStatus: "EXTERNAL ROLE PROPOSAL",
  },
];
